block_text.h File Reference
block_text.h File Reference
The interface for creating, manipulating, and printing blocks.
Functions
void free_block (char **block, int num_elements)
Fress the block from memory.
void print_block (char **text, int num_strings)
Prints the block to console.
char ** blockify (char *text, int text_size)
Creates a block version of text given to the function.
void add_diagonal (char **block, int nuum_elements)
Adds a diagonal element to a created block.
Detailed Description
The interface for creating, manipulating, and printing blocks.
Author
Connor Deakin
E-mail: connortdeakin@gmail.com
Project: Blockify
Date
30/08/2016
Definition in file block_text.h.
Function Documentation
void add_diagonal (char ** block, int num_elements)
Adds a diagonal element to a created block.
Parameters
block The block that a diagonal will be added to
num_elements The number of null terminated string elements in the block
Definition at line 113 of file block_text.c.
Referenced by main().
 {
   int half = (num_elements - 1) / 2;
   int text_size =  (num_elements * 2) - 1;
   for(int c = 1; c < (num_elements - 1); ++c)
   {
     char cur_char = *(*block + (c * 2));
     if(c <= half)
     {
       //Top left
       *(*(block + c) + (c * 2)) = cur_char;
       //Bottom right
       *(*(block + num_elements  - 1 - c) + text_size - 1 - (c * 2)) = cur_char;
     }
     else
     {
       //Top Right
       *(*(block + num_elements - 1 - c) + (c * 2)) = cur_char;
       //Bottom left
       *(*(block + c) + text_size - 1 - (c * 2)) = cur_char;
     }
   }
 }
char** blockify (char * text, int text_size)
Creates a block version of text given to the function.
Parameters
text The text that will be blockified
text_size The length of the text that is to be blockified
Returns
The block created by the blockify function from the text
Definition at line 68 of file block_text.c.
Referenced by main().
 {
   int spaced_size = (text_size * 2) - 1;
   char ** block = (char **)malloc(sizeof(char *) * text_size);
   *block = (char *)malloc(sizeof(char *) * spaced_size);
   *(block + text_size - 1) = (char *)malloc(sizeof(char **) * spaced_size);
   //Top and Bottom
   for(int c = 0; c < spaced_size; ++c)
   {
     if(c % 2 == 0)
     {
       *(*block + c) =  *(text + (c / 2));
       *(*(block + text_size - 1) + spaced_size - 1 - c) = *(text + (c / 2));
     }
     else
     {
       *(*block + c) = ' ';
       *(*(block + text_size - 1) + spaced_size - 1 - c) = ' ';
     }
   }
   //Right and Left
   for(int c = 1; c < (text_size - 1); ++c)
   {
     *(block + c) = (char *)malloc(sizeof(char) * spaced_size);
     // first char
     **(block + c) = *(text + c);
     //spaces
     for(int s = 1; s < (spaced_size - 1); ++s)
       *(*(block + c) + s) = ' ';
     // last char
     *(*(block + c) + (spaced_size - 1)) = *(text + text_size - 1 - c);
   }
   return block;
 }
void free_block (char ** block, int num_elements)
Fress the block from memory.
Parameters
block The block to be freed from memory
num_elements The number of null terminated strings contained in the block
Definition at line 49 of file block_text.c.
Referenced by main().
 {
   for(int str = 0; str < num_elements; ++str)
     free(*(block + str));
   free(block);
 }
void print_block (char ** block, int num_strings)
Prints the block to console.
Parameters
block The block to be printed to the screen
num_strings The number of strings contiained in the block (The length of the input string)
Definition at line 33 of file block_text.c.
Referenced by main().
 {
   for(int str = 0; str < num_strings; ++str)
     printf("%s\n", *(block + str));
 }