options.c File Reference
options.c File Reference
Contains the implementation of all option argument related functions.
#include <getopt.h>
#include <string.h>
#include <stdlib.h>
#include <stdio.h>
#include "../header/options.h"
Functions
void free_options (struct Options option_values)
Frees values from the Options struct that required dynamic memory allocation.
void print_help ()
Prints the help dialog for the program. This is printed if the user makes a mistake or asks for it with the -h or –help options.
struct Options parse_options (int argc, char **argv)
Given the argc and argv from main, this will parse the options given to the Blockify program so the program will work according to the users desire.
Detailed Description
Contains the implementation of all option argument related functions.
Author
Connor Deakin
E-mail: connortdeakin@gmail.com
Project: Blockify
Date
30/08/2016
Functions Include:
free_options
print_help
parse_options
Definition in file options.c.
Function Documentation
void free_options (struct Options option_values)
Frees values from the Options struct that required dynamic memory allocation.
Parameters
option_values The Options struct containing all of the option_values
Definition at line 33 of file options.c.
References Options::text.
Referenced by main().
 {
   free(option_values.text);
 }
struct Options parse_options (int argc, char ** argv)
Given the argc and argv from main, this will parse the options given to the Blockify program so the program will work according to the users desire.
Parameters
argc argc from main
argv argv from main
Returns
An Options struct containing all the information about the options provided
Definition at line 65 of file options.c.
References Options::custom_text, Options::diagonal, Options::print_box, print_help(), and Options::text.
Referenced by main().
 {
   int opt;
   struct Options option_values = {0, "SAMPLETEXT", 0, 1};
   while(1)
   {
     int opt_index = 0;
     int text_size;
     static struct option long_options[] =
     {
       {"diagonal", no_argument,       NULL, 'd'},
       {"text",     required_argument, NULL, 't'},
       {"help",     no_argument,       NULL, 'h'}
     };
     opt = getopt_long(argc, argv, ":dt:h", long_options, &opt_index);
     if(opt == -1)
       break;
     switch (opt)
     {
       case 'd' :
         option_values.diagonal = 1;
         break;
       case 't' :
         text_size = strlen(optarg);
         if(text_size > 0)
         {
           option_values.text = (char *)malloc(sizeof(char) * text_size);
           strcpy(option_values.text, optarg);
           option_values.custom_text = 1;
         }
         break;
       case 'h' :
         print_help();
         option_values.print_box = 0;
         break;
       case '?' :
         printf("The provided option [%c] is not an option.\n", (char)optopt);
         printf("Use --help or -h for help.\n");
         option_values.print_box = 0;
         break;
       case ':' :
         printf("The provided option [%c] requires an argument.\n",
           (char)optopt);
         printf("Use --help or -h for help.\n");
         option_values.print_box = 0;
         break;
     }
   }
   return option_values;
 }